[project]
name = "real-estate-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.135.3",
    "python-jose[cryptography]",
    "passlib[bcrypt]",
    "python-multipart",
    "pandas>=3.0.2",
    "numpy",
    "duckdb",
    "sqlglot",
    "langchain",
    "langchain-openai",
    "langchain-google-genai",
    "langchain-anthropic",
    "langchain-ollama",
    "langchain-community",
    "langgraph",
    "loguru",
    "httpx",
    "tabulate",
    "sqlparse",
    "requests",
    "pyarrow",
    "fastparquet",
    "networkx",
    "unidecode",
    "lxml",
    "scipy",
    "scikit-learn",
    "argon2-cffi",
    "pydantic-settings>=2.13.1",
    "sqlalchemy>=2.0.49",
    "uvicorn>=0.44.0",
    "json-repair>=0.59.4",
    "geopandas>=1.1.4",
    "shapely>=2.1.2",
]
